logging:
  file: ./log/ticketline.server.log
  level.: WARN

spring:
  application:
    name: Ticketline Server
    version: @project.version@
  banner:
    location: banner/banner.txt
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
  profiles:
    active: development

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  info:
    git:
      mode: full
