logging:
  level.: INFO
  level.at.ac.tuwien.inso.sepm.ticketline.server.: INFO
  level.org.hibernate.SQL: INFO
#  level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

application:
  authentication:
    signature-algorithm: HS256
    secret: jwtSecret
    validity-duration: 600
    overlap-duration: 300
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:./database/ticketline;MODE=PostgreSQL;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:/scripts/init.sql'
    username: ticketline
    password: ticketline
    platform: POSTGRESQL
  h2:
    console:
      enabled: true
      access-matcher: "hasIpAddress('10.0.0.0/16') or hasIpAddress('127.0.0.0/8') or hasIpAddress('::1')"